[package]
name = "pcap2cshark"
version = "0.1.1"
authors = ["StefanYohansson <sy.fen0@gmail.com>"]

[dependencies]
docopt = "0.7"
rustc-serialize = "0.3"
curl = "0.4.6"
toml = "0.4"
serde = "1.0.4"
serde_json = "1.0.2"
serde_derive = "1.0.4"